### ISSUE TITLE
Version 1.0 crashes

### ISSUE THREAD

**Issue by gleb-chipiga** [jgonggrijp/pip-review#60]
Ubuntu 17.10, Python 3.6.3, pip 9.0.1

Exception:
Traceback (most recent call last):
  File "/home/gleb/.virtualenvs/dev/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/gleb/.virtualenvs/dev/lib/python3.6/site-packages/pip/commands/list.py", line 157, in run
    packages = self.get_outdated(packages, options)
  File "/home/gleb/.virtualenvs/dev/lib/python3.6/site-packages/pip/commands/list.py", line 168, in get_outdated
    dist for dist in self.iter_packages_latest_infos(packages, options)
  File "/home/gleb/.virtualenvs/dev/lib/python3.6/site-packages/pip/commands/list.py", line 169, in <listcomp>
    if dist.latest_version > dist.parsed_version
TypeError: '>' not supported between instances of 'Version' and 'SetuptoolsVersion'
Traceback (most recent call last):
  File "/home/gleb/.virtualenvs/dev/bin/pip-review", line 11, in <module>
    sys.exit(main())
  File "/home/gleb/.virtualenvs/dev/lib/python3.6/site-packages/pip_review/__main__.py", line 201, in main
    outdated = get_outdated_packages(forwarded)
  File "/home/gleb/.virtualenvs/dev/lib/python3.6/site-packages/pip_review/__main__.py", line 185, in get_outdated_packages
    output = check_output(command).decode('utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/gleb/.virtualenvs/dev/bin/python3', '-m', 'pip', 'list', '--outdated', '--disable-pip-version-check', '--format=json']' returned non-zero exit status 2.

**Comment by jgonggrijp** [comment]
The last line of your traceback is telling me that `pip list` is actually the crashing program. It appears you also reported the problem there: https://github.com/pypa/pip/issues/4980. Closing here.

**Comment by jgonggrijp** [comment]
For future reference: the solution is `pip3 install --ignore-installed pip`.
