### ISSUE TITLE
pip-review hangs when running

### ISSUE THREAD

**Issue by texasreddog** [jgonggrijp/pip-review#64]
I've been using pip-review for a while, but it has just seemed to stop working recently.  when I try to run it on the command line with the -i option, it just sits and hangs and never returns anything.  I finally have to Ctrl-C to get out of it, then it shows:

C:\Users>pip-review -i
Operation cancelled by user
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\pip-review.exe\__main__.py", line 9, in <module>
  File "c:\Python27\Lib\site-packages\pip_review\__main__.py", line 201, in main
    outdated = get_outdated_packages(forwarded)
  File "c:\Python27\Lib\site-packages\pip_review\__main__.py", line 185, in get_outdated_packages
    output = check_output(command).decode('utf-8')
  File "c:\python27\lib\subprocess.py", line 567, in check_output
    output, unused_err = process.communicate()
  File "c:\python27\lib\subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "c:\python27\lib\subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

I'm using Python 2.7.11 on a Windows 7 machine.

**Comment by jgonggrijp** [comment]
Thanks for reporting this. Which version of pip-review and which version of pip are you using? Did you recently update either of those?

**Comment by texasreddog** [comment]
I'm using pip version 18.0, which was recently updated.  pip-review is at 1.0, which I think is the latest.

**Comment by jgonggrijp** [comment]
It may very well be the case that pip-review 1.0 (which is indeed the latest version) isn't compatible with pip 18. I haven't tested this combination yet. I'll look into it.

**Comment by jgonggrijp** [comment]
On my mac, pip-review 1.0 works fine with pip 18, both under python 2.7 and python 3.5. So if this is a real issue, it is probably windows-specific. I need help from a Windows user to figure out what is causing this issue. @texasreddog, could you give this a try, perhaps with a fresh virtual environment to rule out side effects from installed other packages?
